server: 
  port: 9008
spring: 
  application:  
    name: user #指定服务名
  datasource:  
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.53.232:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: 1234
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 47.98.53.232
  rabbitmq:
    host: 47.98.53.232