server:
  port: 9010
spring:
  application:
    name: friend
  datasource:   # 配置数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.53.232:3306/tensquare_friend?characterEncoding=utf-8
    username: root
    password: 1234
  jpa:      # 配置jpa
    database: mysql
    show-sql: true
  main:
    allow-bean-definition-overriding: true

jwt:
  config:
    # 加盐
    key: itcast
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true     # 跨域访问
